project:
  type: website

website:
  title: "musings"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/bmoscona
      - icon: linkedin
        href: https://www.linkedin.com/in/ben-moscona/
format:
  html:
    theme: journal
    css: styles.css



